<?php 
/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/09/2016
 */

namespace MagicTelecomAPILib\Models;

use JsonSerializable;

class RoutingBase implements JsonSerializable {
    /**
     * TODO: Write general description for this property
     * @param string $logic public property
     */
    protected $logic;

    /**
     * TODO: Write general description for this property
     * @param array $endpoints public property
     */
    protected $endpoints;

    /**
     * Constructor to set initial or default values of member properties
	 * @param   string            $logic       Initialization value for the property $this->logic    
	 * @param   array             $endpoints   Initialization value for the property $this->endpoints
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->logic     = func_get_arg(0);
            $this->endpoints = func_get_arg(1);
        }
    }

    /**
     * Return a property of the response if it exists.
     * Possibilities include: code, raw_body, headers, body (if the response is json-decodable)
     * @return mixed
     */
    public function __get($property)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            $value = $this->$property;
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                return utf8_encode($value);
            }
            else {
                return $value;
            }
        }
    }
    
    /**
     * Set the properties of this object
     * @param string $property the property name
     * @param mixed $value the property value
     */
    public function __set($property, $value)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                $this->$property = utf8_encode($value);
            }
            else {
                $this->$property = $value;
            }
        }

        return $this;
    }

    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['logic']     = $this->logic;
        $json['endpoints'] = $this->endpoints;
        return $json;
    }
}