<?php 
/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 03/21/2016
 */

namespace MagicTelecomAPILib\Models;

use JsonSerializable;

class Token implements JsonSerializable {
    /**
     * TODO: Write general description for this property
     * @param bool $isActive public property
     */
    protected $isActive;

    /**
     * TODO: Write general description for this property
     * @param string $token public property
     */
    protected $token;

    /**
     * TODO: Write general description for this property
     * @param string $created public property
     */
    protected $created;

    /**
     * Constructor to set initial or default values of member properties
	 * @param   bool              $isActive    Initialization value for the property $this->isActive 
	 * @param   string            $token       Initialization value for the property $this->token    
	 * @param   string            $created     Initialization value for the property $this->created  
     */
    public function __construct()
    {
        if(3 == func_num_args())
        {
            $this->isActive  = func_get_arg(0);
            $this->token     = func_get_arg(1);
            $this->created   = func_get_arg(2);
        }
    }

    /**
     * Return a property of the response if it exists.
     * Possibilities include: code, raw_body, headers, body (if the response is json-decodable)
     * @return mixed
     */
    public function __get($property)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            $value = $this->$property;
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                return utf8_encode($value);
            }
            else {
                return $value;
            }
        }
    }
    
    /**
     * Set the properties of this object
     * @param string $property the property name
     * @param mixed $value the property value
     */
    public function __set($property, $value)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                $this->$property = utf8_encode($value);
            }
            else {
                $this->$property = $value;
            }
        }

        return $this;
    }

    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['is_active'] = $this->isActive;
        $json['token']     = $this->token;
        $json['created']   = $this->created;
        return $json;
    }
}