<?php 
/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/04/2016
 */

namespace MagicTelecomAPILib\Models;

use JsonSerializable;

class TrunkChannelsItem extends Item implements JsonSerializable {
    /**
     * TODO: Write general description for this property
     * @param int $additionalChannels public property
     */
    protected $additionalChannels;

    /**
     * TODO: Write general description for this property
     * @param int $trunkId public property
     */
    protected $trunkId;

    /**
     * Constructor to set initial or default values of member properties
	 * @param   int               $additionalChannels       Initialization value for the property $this->additionalChannels    
	 * @param   int               $trunkId            Initialization value for the property $this->trunkId     
     */
    public function __construct()
    {
        if(2 == func_num_args())
        {
            $this->additionalChannels     = func_get_arg(0);
            $this->trunkId          	  = func_get_arg(1);;
        }
    }

    /**
     * Return a property of the response if it exists.
     * Possibilities include: code, raw_body, headers, body (if the response is json-decodable)
     * @return mixed
     */
    public function __get($property)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            $value = $this->$property;
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                return utf8_encode($value);
            }
            else {
                return $value;
            }
        }
    }
    
    /**
     * Set the properties of this object
     * @param string $property the property name
     * @param mixed $value the property value
     */
    public function __set($property, $value)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                $this->$property = utf8_encode($value);
            }
            else {
                $this->$property = $value;
            }
        }

        return $this;
    }

    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['additional_channels']  = $this->channels;
        $json['trunk_id'] 			  = $this->trunkHandle;
        $json = array_merge($json, parent::jsonSerialize());
        return $json;
    }
}