<?php 
/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/04/2016
 */

namespace MagicTelecomAPILib\Models;

use JsonSerializable;

class TrunkItem extends Item implements JsonSerializable {
    /**
     * TODO: Write general description for this property
     * @param int $channels public property
     */
    protected $channels;

    /**
     * TODO: Write general description for this property
     * @param string $trunkHandle public property
     */
    protected $trunkHandle;

    /**
     * TODO: Write general description for this property
     * @param string $sipUri public property
     */
    protected $sipUri;

    /**
     * TODO: Write general description for this property
     * @param string $attributes public property
     */
    protected $attributes;

    /**
     * TODO: Write general description for this property
     * @param Routing $routing public property
     */
    protected $routing;

    /**
     * Constructor to set initial or default values of member properties
	 * @param   int               $channels       Initialization value for the property $this->channels    
	 * @param   string            $trunkHandle    Initialization value for the property $this->trunkHandle 
	 * @param   string            $sipUri         Initialization value for the property $this->sipUri      
	 * @param   string            $attributes     Initialization value for the property $this->attributes  
	 * @param   Routing           $routing        Initialization value for the property $this->routing     
     */
    public function __construct()
    {
        if(5 == func_num_args())
        {
            $this->channels     = func_get_arg(0);
            $this->trunkHandle  = func_get_arg(1);
            $this->sipUri       = func_get_arg(2);
            $this->attributes   = func_get_arg(3);
            $this->routing      = func_get_arg(4);
        }
    }

    /**
     * Return a property of the response if it exists.
     * Possibilities include: code, raw_body, headers, body (if the response is json-decodable)
     * @return mixed
     */
    public function __get($property)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            $value = $this->$property;
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                return utf8_encode($value);
            }
            else {
                return $value;
            }
        }
    }
    
    /**
     * Set the properties of this object
     * @param string $property the property name
     * @param mixed $value the property value
     */
    public function __set($property, $value)
    {
        if (property_exists($this, $property)) {
            //UTF-8 is recommended for correct JSON serialization
            if (is_string($value) && mb_detect_encoding($value, "UTF-8", TRUE) != "UTF-8") {
                $this->$property = utf8_encode($value);
            }
            else {
                $this->$property = $value;
            }
        }

        return $this;
    }

    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['channels']     = $this->channels;
        $json['trunk_handle'] = $this->trunkHandle;
        $json['sip_uri']      = $this->sipUri;
        $json['attributes']   = $this->attributes;
        $json['_routing']     = $this->routing;
        $json = array_merge($json, parent::jsonSerialize());
        return $json;
    }
}