<?php
/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 12/08/2015
 */

namespace MagicTelecomAPILib;

class Configuration {
    //The base Uri for API calls
    public static $BASEURI = 'https://api.magictelecom.dev/app_dev.php';

}
