<?php
/*
 * MagicTelecomAPILib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 12/08/2015
 */

namespace MagicTelecomAPILib;

class CustomAuthUtility {
    /**
    * Appends the necessary Custom Authentication credentials for making this authorized call
    * @param HttpRequest $request The out going request to access the resource
    */
    public static function appendCustomAuthParams($request)
    {
        // TODO: Add your custom authentication here
		// The following properties are available to use
		//     Configuration::$xWSSE
		// 
		// ie. Add a header through:
		//     $request.headers(array("key" => "value"));
    }
}